# Generated by Django 5.2 on 2026-05-21 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='import_type',
            field=models.CharField(choices=[('AUTO', 'Auto-detect'), ('INSTITUTIONS', 'Institutions'), ('STUDENTS', 'Students'), ('PROGRAMMES', 'Programmes'), ('ENROLLMENTS', 'Enrollments'), ('INDICATORS', 'Indicator Data')], default='AUTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL),
        ),
    ]
