# Generated by Django 5.2 on 2026-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importhistory_import_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='failed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='flagged_records',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
