# Generated by Django 5.2 on 2026-05-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PUBLIC', 'Public University'), ('PRIVATE', 'Private University'), ('COLLEGE', 'College')], max_length=20)),
                ('province', models.CharField(choices=[('LUSAKA', 'Lusaka'), ('COPPERBELT', 'Copperbelt'), ('CENTRAL', 'Central'), ('SOUTHERN', 'Southern'), ('EASTERN', 'Eastern'), ('WESTERN', 'Western'), ('NORTHERN', 'Northern'), ('NORTH_WESTERN', 'North Western'), ('LUAPULA', 'Luapula'), ('MUCHINGA', 'Muchinga')], max_length=50)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
