# Generated by Django 5.2 on 2026-05-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'Public University'), ('PRIVATE', 'Private University'), ('COLLEGE', 'College'), ('TECHNICAL', 'Technical/Vocational')], max_length=20),
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, choices=[('LUSAKA', 'Lusaka'), ('COPPERBELT', 'Copperbelt'), ('CENTRAL', 'Central'), ('SOUTHERN', 'Southern'), ('EASTERN', 'Eastern'), ('WESTERN', 'Western'), ('NORTHERN', 'Northern'), ('NORTH_WESTERN', 'North Western'), ('LUAPULA', 'Luapula'), ('MUCHINGA', 'Muchinga')], max_length=50, null=True)),
                ('is_main_campus', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='institutions.institution')),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['institution', 'name'],
            },
        ),
    ]
