# Generated by Django 5.2 on 2026-05-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pattern', models.CharField(help_text="The value to look for (e.g., 'UNZA')", max_length=255)),
                ('replacement', models.CharField(help_text="The normalized value (e.g., 'University of Zambia')", max_length=255)),
                ('category', models.CharField(choices=[('INSTITUTION', 'Institution'), ('PROGRAMME', 'Programme'), ('QUALIFICATION', 'Qualification'), ('PROVINCE', 'Province')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'pattern'],
            },
        ),
    ]
