# Generated by Django 5.2 on 2026-05-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_update_models'),
        ('institutions', '0002_institution_email_institution_established_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institutions.institution'),
        ),
    ]
