# Generated by Django 5.2 on 2026-05-14 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SDG4', 'SDG 4 - Quality Education'), ('CESA', 'CESA - Continental Education Strategy'), ('HEA_KPI', 'HEA Key Performance Indicators'), ('INSTITUTIONAL', 'Institutional KPIs')], max_length=50)),
                ('formula', models.TextField(help_text='LaTeX or descriptive formula')),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='Percentage', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'ordering': ['-year', 'indicator'],
                'unique_together': {('indicator', 'institution', 'year')},
            },
        ),
    ]
